default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Parashu
  username: postgres
  password: Parashu
  host: localhost
  port: 5433

test:
  <<: *default
  database: deploy_test

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  pool: 5
  url: <%= ENV["DATABASE_URL"] %>
  database: parashu_db
  username: preetham
  password: "rfsMa95sf53uOjXfMZf8IYUq8dFvaWwd"
